version: "3.3"
services:
  db:
    image: postgres:latest
    container_name: pa5a-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: pa5a
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pa5a
    #volumes:
    ports:
      - "5432:5432"
  #web:
    #image: node:14.16.0-alpine3.10
    #container_name: pa5a-web
    #restart: unless-stopped
    #depends_on:
      #- db
    #working_dir: /app
    #volumes:
      #- ./application:/app
    #command: sh -c "npm install && npm tun watch"
    #ports:
      #- "80:80"
      #- "443:443"